2021/05/31 16:25:54 [error] 43#43: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.5, server: ee.kobo.local, request: "GET / HTTP/1.1", upstream: "http://172.22.0.3:8005/", host: "ee.docker.internal"
2021/05/31 16:26:04 [error] 43#43: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.5, server: ee.kobo.local, request: "GET / HTTP/1.1", upstream: "http://172.22.0.3:8005/", host: "ee.docker.internal"
2021/05/31 16:26:14 [error] 43#43: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.5, server: ee.kobo.local, request: "GET / HTTP/1.1", upstream: "http://172.22.0.3:8005/", host: "ee.docker.internal"
2021/05/31 16:26:24 [error] 43#43: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.5, server: ee.kobo.local, request: "GET / HTTP/1.1", upstream: "http://172.22.0.3:8005/", host: "ee.docker.internal"
